from __future__ import annotations

from typing import Any


def get_seed_recent_games() -> list[dict[str, Any]]:
    return [
        {
            "game_id": "recent-001",
            "game_date": "2026-05-22",
            "home_team": "Cleveland Cavaliers",
            "away_team": "New York Knicks",
            "status": "Final",
            "home_score": 105,
            "away_score": 112,
        },
        {
            "game_id": "recent-002",
            "game_date": "2026-05-24",
            "home_team": "New York Knicks",
            "away_team": "Cleveland Cavaliers",
            "status": "Final",
            "home_score": 98,
            "away_score": 103,
        },
        {
            "game_id": "recent-003",
            "game_date": "2026-05-26",
            "home_team": "Cleveland Cavaliers",
            "away_team": "New York Knicks",
            "status": "Final",
            "home_score": 97,
            "away_score": 108,
        },
    ]


def get_seed_scoreboard() -> list[dict[str, Any]]:
    return [
        {
            "game_id": "seed-001",
            "game_date": "2026-05-16",
            "home_team": "Los Angeles Lakers",
            "away_team": "Golden State Warriors",
            "status": "Final",
            "home_score": 112,
            "away_score": 108,
        },
        {
            "game_id": "seed-002",
            "game_date": "2026-05-16",
            "home_team": "Boston Celtics",
            "away_team": "New York Knicks",
            "status": "Live",
            "home_score": 84,
            "away_score": 81,
        },
        {
            "game_id": "seed-003",
            "game_date": "2026-05-17",
            "home_team": "Denver Nuggets",
            "away_team": "Dallas Mavericks",
            "status": "Scheduled",
            "home_score": None,
            "away_score": None,
        },
    ]


def get_seed_boxscore(game_id: str) -> list[dict[str, Any]]:
    _data: dict[str, list[dict[str, Any]]] = {
        "seed-001": [
            # Lakers (home)
            {"player_id": 2544,    "player_name": "LeBron James",         "team": "LAL", "side": "home", "minutes": "36:21", "points": 28, "rebounds": 8, "assists": 9, "steals": 2, "blocks": 1, "fg_pct": 55.6, "fg3_pct": 40.0, "turnovers": 3},
            {"player_id": 203076,  "player_name": "Anthony Davis",        "team": "LAL", "side": "home", "minutes": "34:05", "points": 26, "rebounds": 14, "assists": 3, "steals": 1, "blocks": 3, "fg_pct": 60.0, "fg3_pct": 0.0,  "turnovers": 2},
            {"player_id": 203507,  "player_name": "Giannis A.",           "team": "LAL", "side": "home", "minutes": "30:00", "points": 18, "rebounds": 7,  "assists": 4, "steals": 1, "blocks": 1, "fg_pct": 50.0, "fg3_pct": 0.0,  "turnovers": 2},
            {"player_id": 1630162, "player_name": "Anthony Edwards",      "team": "LAL", "side": "home", "minutes": "32:10", "points": 22, "rebounds": 5,  "assists": 5, "steals": 1, "blocks": 0, "fg_pct": 47.6, "fg3_pct": 42.9, "turnovers": 3},
            {"player_id": 1628369, "player_name": "Jayson Tatum",         "team": "LAL", "side": "home", "minutes": "33:45", "points": 18, "rebounds": 6,  "assists": 4, "steals": 1, "blocks": 0, "fg_pct": 45.0, "fg3_pct": 33.3, "turnovers": 1},
            # Warriors (away)
            {"player_id": 201939,  "player_name": "Stephen Curry",        "team": "GSW", "side": "away", "minutes": "36:00", "points": 31, "rebounds": 5,  "assists": 6, "steals": 1, "blocks": 0, "fg_pct": 48.1, "fg3_pct": 46.2, "turnovers": 3},
            {"player_id": 1629029, "player_name": "Luka Doncic",          "team": "GSW", "side": "away", "minutes": "35:20", "points": 29, "rebounds": 9,  "assists": 8, "steals": 1, "blocks": 0, "fg_pct": 51.7, "fg3_pct": 37.5, "turnovers": 4},
            {"player_id": 201142,  "player_name": "Kevin Durant",         "team": "GSW", "side": "away", "minutes": "34:00", "points": 25, "rebounds": 7,  "assists": 4, "steals": 0, "blocks": 2, "fg_pct": 53.8, "fg3_pct": 33.3, "turnovers": 2},
            {"player_id": 1626164, "player_name": "Devin Booker",         "team": "GSW", "side": "away", "minutes": "30:15", "points": 16, "rebounds": 4,  "assists": 5, "steals": 1, "blocks": 0, "fg_pct": 40.0, "fg3_pct": 30.0, "turnovers": 2},
            {"player_id": 1641705, "player_name": "Victor Wembanyama",    "team": "GSW", "side": "away", "minutes": "28:50", "points": 7,  "rebounds": 8,  "assists": 2, "steals": 1, "blocks": 4, "fg_pct": 33.3, "fg3_pct": 0.0,  "turnovers": 1},
        ],
        "seed-002": [
            # Celtics (home)
            {"player_id": 1628369, "player_name": "Jayson Tatum",         "team": "BOS", "side": "home", "minutes": "24:00", "points": 22, "rebounds": 7,  "assists": 3, "steals": 1, "blocks": 1, "fg_pct": 50.0, "fg3_pct": 40.0, "turnovers": 2},
            {"player_id": 1628389, "player_name": "Jaylen Brown",         "team": "BOS", "side": "home", "minutes": "22:30", "points": 18, "rebounds": 4,  "assists": 2, "steals": 2, "blocks": 0, "fg_pct": 46.2, "fg3_pct": 33.3, "turnovers": 1},
            {"player_id": 203507,  "player_name": "Giannis A.",           "team": "BOS", "side": "home", "minutes": "23:15", "points": 15, "rebounds": 9,  "assists": 4, "steals": 1, "blocks": 2, "fg_pct": 52.9, "fg3_pct": 0.0,  "turnovers": 2},
            {"player_id": 1626169, "player_name": "Pascal Siakam",        "team": "BOS", "side": "home", "minutes": "20:00", "points": 12, "rebounds": 6,  "assists": 2, "steals": 0, "blocks": 1, "fg_pct": 44.4, "fg3_pct": 0.0,  "turnovers": 1},
            {"player_id": 1630530, "player_name": "Evan Mobley",          "team": "BOS", "side": "home", "minutes": "21:00", "points": 17, "rebounds": 10, "assists": 2, "steals": 1, "blocks": 3, "fg_pct": 58.3, "fg3_pct": 50.0, "turnovers": 1},
            # Knicks (away)
            {"player_id": 1628778, "player_name": "Mikal Bridges",        "team": "NYK", "side": "away", "minutes": "23:00", "points": 20, "rebounds": 5,  "assists": 3, "steals": 2, "blocks": 0, "fg_pct": 50.0, "fg3_pct": 42.9, "turnovers": 1},
            {"player_id": 1188555, "player_name": "Karl-Anthony Towns",   "team": "NYK", "side": "away", "minutes": "22:00", "points": 24, "rebounds": 9,  "assists": 2, "steals": 0, "blocks": 1, "fg_pct": 57.1, "fg3_pct": 40.0, "turnovers": 2},
            {"player_id": 1628386, "player_name": "Donovan Mitchell",     "team": "NYK", "side": "away", "minutes": "24:00", "points": 19, "rebounds": 4,  "assists": 5, "steals": 2, "blocks": 0, "fg_pct": 44.4, "fg3_pct": 33.3, "turnovers": 2},
            {"player_id": 1629649, "player_name": "Scottie Barnes",       "team": "NYK", "side": "away", "minutes": "21:30", "points": 13, "rebounds": 7,  "assists": 5, "steals": 1, "blocks": 1, "fg_pct": 46.2, "fg3_pct": 33.3, "turnovers": 2},
            {"player_id": 1628960, "player_name": "Bam Adebayo",          "team": "NYK", "side": "away", "minutes": "20:45", "points": 5,  "rebounds": 8,  "assists": 3, "steals": 1, "blocks": 1, "fg_pct": 33.3, "fg3_pct": 0.0,  "turnovers": 1},
        ],
        "seed-003": [],
        # 2026 Finals — Knicks vs Cavaliers
        "recent-001": [
            # Cavaliers (home) — lost 105-112
            {"player_id": 1628386, "player_name": "Donovan Mitchell", "team": "CLE", "side": "home", "minutes": "38:20", "points": 32, "rebounds": 5, "assists": 7, "steals": 2, "blocks": 0, "fg_pct": 48.0, "fg3_pct": 42.9, "turnovers": 4},
            {"player_id": 1630530, "player_name": "Evan Mobley",      "team": "CLE", "side": "home", "minutes": "36:10", "points": 24, "rebounds": 11, "assists": 3, "steals": 1, "blocks": 2, "fg_pct": 55.6, "fg3_pct": 0.0,  "turnovers": 2},
            {"player_id": 1629636, "player_name": "Darius Garland",   "team": "CLE", "side": "home", "minutes": "34:00", "points": 18, "rebounds": 3,  "assists": 9, "steals": 1, "blocks": 0, "fg_pct": 40.0, "fg3_pct": 33.3, "turnovers": 3},
            {"player_id": 1628456, "player_name": "Jarrett Allen",    "team": "CLE", "side": "home", "minutes": "28:00", "points": 14, "rebounds": 9,  "assists": 1, "steals": 0, "blocks": 2, "fg_pct": 70.0, "fg3_pct": 0.0,  "turnovers": 1},
            {"player_id": 1629622, "player_name": "Max Strus",        "team": "CLE", "side": "home", "minutes": "25:30", "points": 17, "rebounds": 4,  "assists": 2, "steals": 1, "blocks": 0, "fg_pct": 50.0, "fg3_pct": 44.4, "turnovers": 1},
            # Knicks (away) — won 112-105
            {"player_id": 1628973, "player_name": "Jalen Brunson",    "team": "NYK", "side": "away", "minutes": "39:00", "points": 34, "rebounds": 4,  "assists": 8, "steals": 1, "blocks": 0, "fg_pct": 51.9, "fg3_pct": 42.9, "turnovers": 3},
            {"player_id": 1188555, "player_name": "Karl-Anthony Towns","team": "NYK", "side": "away", "minutes": "35:20", "points": 27, "rebounds": 11, "assists": 3, "steals": 0, "blocks": 1, "fg_pct": 60.0, "fg3_pct": 40.0, "turnovers": 2},
            {"player_id": 1628778, "player_name": "Mikal Bridges",    "team": "NYK", "side": "away", "minutes": "36:00", "points": 22, "rebounds": 6,  "assists": 4, "steals": 3, "blocks": 1, "fg_pct": 47.1, "fg3_pct": 40.0, "turnovers": 1},
            {"player_id": 1628384, "player_name": "OG Anunoby",       "team": "NYK", "side": "away", "minutes": "34:10", "points": 18, "rebounds": 7,  "assists": 2, "steals": 2, "blocks": 1, "fg_pct": 52.9, "fg3_pct": 40.0, "turnovers": 1},
            {"player_id": 203944,  "player_name": "Julius Randle",    "team": "NYK", "side": "away", "minutes": "30:00", "points": 11, "rebounds": 8,  "assists": 4, "steals": 0, "blocks": 0, "fg_pct": 37.5, "fg3_pct": 0.0,  "turnovers": 2},
        ],
        "recent-002": [
            # Knicks (home) — lost 98-103
            {"player_id": 1628973, "player_name": "Jalen Brunson",    "team": "NYK", "side": "home", "minutes": "40:00", "points": 29, "rebounds": 3,  "assists": 6, "steals": 1, "blocks": 0, "fg_pct": 44.4, "fg3_pct": 33.3, "turnovers": 4},
            {"player_id": 1188555, "player_name": "Karl-Anthony Towns","team": "NYK", "side": "home", "minutes": "34:00", "points": 22, "rebounds": 9,  "assists": 2, "steals": 0, "blocks": 1, "fg_pct": 52.4, "fg3_pct": 33.3, "turnovers": 3},
            {"player_id": 1628778, "player_name": "Mikal Bridges",    "team": "NYK", "side": "home", "minutes": "37:00", "points": 19, "rebounds": 5,  "assists": 3, "steals": 2, "blocks": 0, "fg_pct": 45.8, "fg3_pct": 37.5, "turnovers": 1},
            {"player_id": 1628384, "player_name": "OG Anunoby",       "team": "NYK", "side": "home", "minutes": "33:00", "points": 16, "rebounds": 6,  "assists": 1, "steals": 1, "blocks": 2, "fg_pct": 53.3, "fg3_pct": 50.0, "turnovers": 0},
            {"player_id": 203944,  "player_name": "Julius Randle",    "team": "NYK", "side": "home", "minutes": "28:00", "points": 12, "rebounds": 7,  "assists": 5, "steals": 1, "blocks": 0, "fg_pct": 41.7, "fg3_pct": 0.0,  "turnovers": 3},
            # Cavaliers (away) — won 103-98
            {"player_id": 1628386, "player_name": "Donovan Mitchell", "team": "CLE", "side": "away", "minutes": "39:00", "points": 35, "rebounds": 6,  "assists": 5, "steals": 2, "blocks": 0, "fg_pct": 50.0, "fg3_pct": 44.4, "turnovers": 3},
            {"player_id": 1630530, "player_name": "Evan Mobley",      "team": "CLE", "side": "away", "minutes": "36:30", "points": 21, "rebounds": 12, "assists": 4, "steals": 2, "blocks": 3, "fg_pct": 56.3, "fg3_pct": 0.0,  "turnovers": 1},
            {"player_id": 1629636, "player_name": "Darius Garland",   "team": "CLE", "side": "away", "minutes": "35:00", "points": 23, "rebounds": 4,  "assists": 10, "steals": 1, "blocks": 0, "fg_pct": 47.6, "fg3_pct": 37.5, "turnovers": 2},
            {"player_id": 1628456, "player_name": "Jarrett Allen",    "team": "CLE", "side": "away", "minutes": "26:00", "points": 12, "rebounds": 8,  "assists": 2, "steals": 0, "blocks": 1, "fg_pct": 66.7, "fg3_pct": 0.0,  "turnovers": 2},
            {"player_id": 1629622, "player_name": "Max Strus",        "team": "CLE", "side": "away", "minutes": "22:00", "points": 12, "rebounds": 3,  "assists": 1, "steals": 0, "blocks": 0, "fg_pct": 44.4, "fg3_pct": 40.0, "turnovers": 1},
        ],
        "recent-003": [
            # Cavaliers (home) — lost 97-108
            {"player_id": 1628386, "player_name": "Donovan Mitchell", "team": "CLE", "side": "home", "minutes": "37:00", "points": 28, "rebounds": 4,  "assists": 6, "steals": 1, "blocks": 0, "fg_pct": 45.2, "fg3_pct": 38.5, "turnovers": 5},
            {"player_id": 1630530, "player_name": "Evan Mobley",      "team": "CLE", "side": "home", "minutes": "35:20", "points": 20, "rebounds": 10, "assists": 2, "steals": 1, "blocks": 2, "fg_pct": 53.8, "fg3_pct": 0.0,  "turnovers": 2},
            {"player_id": 1629636, "player_name": "Darius Garland",   "team": "CLE", "side": "home", "minutes": "33:00", "points": 22, "rebounds": 3,  "assists": 7, "steals": 0, "blocks": 0, "fg_pct": 46.7, "fg3_pct": 40.0, "turnovers": 3},
            {"player_id": 1628456, "player_name": "Jarrett Allen",    "team": "CLE", "side": "home", "minutes": "27:00", "points": 13, "rebounds": 8,  "assists": 1, "steals": 0, "blocks": 1, "fg_pct": 72.7, "fg3_pct": 0.0,  "turnovers": 1},
            {"player_id": 1629622, "player_name": "Max Strus",        "team": "CLE", "side": "home", "minutes": "24:00", "points": 14, "rebounds": 2,  "assists": 1, "steals": 0, "blocks": 0, "fg_pct": 50.0, "fg3_pct": 42.9, "turnovers": 0},
            # Knicks (away) — won 108-97
            {"player_id": 1628973, "player_name": "Jalen Brunson",    "team": "NYK", "side": "away", "minutes": "38:30", "points": 33, "rebounds": 4,  "assists": 9, "steals": 1, "blocks": 0, "fg_pct": 52.4, "fg3_pct": 44.4, "turnovers": 2},
            {"player_id": 1188555, "player_name": "Karl-Anthony Towns","team": "NYK", "side": "away", "minutes": "36:00", "points": 26, "rebounds": 13, "assists": 2, "steals": 1, "blocks": 2, "fg_pct": 57.9, "fg3_pct": 50.0, "turnovers": 2},
            {"player_id": 1628778, "player_name": "Mikal Bridges",    "team": "NYK", "side": "away", "minutes": "35:00", "points": 24, "rebounds": 5,  "assists": 4, "steals": 2, "blocks": 1, "fg_pct": 50.0, "fg3_pct": 41.7, "turnovers": 1},
            {"player_id": 1628384, "player_name": "OG Anunoby",       "team": "NYK", "side": "away", "minutes": "32:00", "points": 15, "rebounds": 5,  "assists": 2, "steals": 3, "blocks": 0, "fg_pct": 50.0, "fg3_pct": 42.9, "turnovers": 1},
            {"player_id": 203944,  "player_name": "Julius Randle",    "team": "NYK", "side": "away", "minutes": "29:00", "points": 10, "rebounds": 9,  "assists": 5, "steals": 0, "blocks": 1, "fg_pct": 40.0, "fg3_pct": 0.0,  "turnovers": 2},
        ],
    }
    return _data.get(game_id, [])


def get_seed_players() -> list[dict[str, Any]]:
    return [
        # Point Guards
        {
            "id": 201939,
            "name": "Stephen Curry",
            "team": "GSW",
            "position": "PG",
            "points": 26.4,
            "rebounds": 4.5,
            "assists": 5.1,
            "steals": 0.9,
            "blocks": 0.4,
            "turnovers": 2.8,
            "image_url": None,
        },
        {
            "id": 1629029,
            "name": "Luka Doncic",
            "team": "DAL",
            "position": "PG",
            "points": 33.9,
            "rebounds": 9.2,
            "assists": 9.8,
            "steals": 1.4,
            "blocks": 0.5,
            "turnovers": 4.0,
            "image_url": None,
        },
        {
            "id": 1628983,
            "name": "Shai Gilgeous-Alexander",
            "team": "OKC",
            "position": "PG",
            "points": 30.1,
            "rebounds": 5.5,
            "assists": 6.2,
            "steals": 2.0,
            "blocks": 0.9,
            "turnovers": 2.2,
            "image_url": None,
        },
        {
            "id": 1629630,
            "name": "Ja Morant",
            "team": "MEM",
            "position": "PG",
            "points": 25.1,
            "rebounds": 5.6,
            "assists": 8.1,
            "steals": 1.1,
            "blocks": 0.5,
            "turnovers": 3.4,
            "image_url": None,
        },
        {
            "id": 1631094,
            "name": "Paolo Banchero",
            "team": "ORL",
            "position": "PG",
            "points": 22.6,
            "rebounds": 6.9,
            "assists": 5.4,
            "steals": 1.0,
            "blocks": 0.5,
            "turnovers": 3.3,
            "image_url": None,
        },
        {
            "id": 203110,
            "name": "Damian Lillard",
            "team": "MIL",
            "position": "PG",
            "points": 24.3,
            "rebounds": 4.4,
            "assists": 7.3,
            "steals": 0.9,
            "blocks": 0.3,
            "turnovers": 2.9,
            "image_url": None,
        },
        # Shooting Guards
        {
            "id": 1630162,
            "name": "Anthony Edwards",
            "team": "MIN",
            "position": "SG",
            "points": 25.9,
            "rebounds": 5.4,
            "assists": 5.1,
            "steals": 1.3,
            "blocks": 0.5,
            "turnovers": 3.1,
            "image_url": None,
        },
        {
            "id": 1628386,
            "name": "Donovan Mitchell",
            "team": "CLE",
            "position": "SG",
            "points": 26.6,
            "rebounds": 5.1,
            "assists": 6.1,
            "steals": 1.6,
            "blocks": 0.4,
            "turnovers": 3.0,
            "image_url": None,
        },
        {
            "id": 1626164,
            "name": "Devin Booker",
            "team": "PHX",
            "position": "SG",
            "points": 27.1,
            "rebounds": 4.5,
            "assists": 6.9,
            "steals": 1.1,
            "blocks": 0.3,
            "turnovers": 3.2,
            "image_url": None,
        },
        {
            "id": 203897,
            "name": "Zach LaVine",
            "team": "CHI",
            "position": "SG",
            "points": 22.5,
            "rebounds": 4.5,
            "assists": 4.2,
            "steals": 0.9,
            "blocks": 0.4,
            "turnovers": 2.5,
            "image_url": None,
        },
        # Small Forwards
        {
            "id": 2544,
            "name": "LeBron James",
            "team": "LAL",
            "position": "SF",
            "points": 25.7,
            "rebounds": 7.3,
            "assists": 8.3,
            "steals": 1.3,
            "blocks": 0.6,
            "turnovers": 3.5,
            "image_url": None,
        },
        {
            "id": 203507,
            "name": "Giannis Antetokounmpo",
            "team": "MIL",
            "position": "SF",
            "points": 30.4,
            "rebounds": 11.5,
            "assists": 6.5,
            "steals": 1.2,
            "blocks": 1.1,
            "turnovers": 3.4,
            "image_url": None,
        },
        {
            "id": 201142,
            "name": "Kevin Durant",
            "team": "PHX",
            "position": "SF",
            "points": 27.1,
            "rebounds": 6.6,
            "assists": 5.0,
            "steals": 0.9,
            "blocks": 1.2,
            "turnovers": 3.3,
            "image_url": None,
        },
        {
            "id": 1628369,
            "name": "Jayson Tatum",
            "team": "BOS",
            "position": "SF",
            "points": 26.9,
            "rebounds": 8.1,
            "assists": 4.9,
            "steals": 1.0,
            "blocks": 0.6,
            "turnovers": 2.5,
            "image_url": None,
        },
        {
            "id": 1629627,
            "name": "Zion Williamson",
            "team": "NOP",
            "position": "SF",
            "points": 22.9,
            "rebounds": 5.8,
            "assists": 5.0,
            "steals": 1.1,
            "blocks": 0.7,
            "turnovers": 2.8,
            "image_url": None,
        },
        {
            "id": 1628389,
            "name": "Jaylen Brown",
            "team": "BOS",
            "position": "SF",
            "points": 23.0,
            "rebounds": 5.5,
            "assists": 3.6,
            "steals": 1.1,
            "blocks": 0.4,
            "turnovers": 2.6,
            "image_url": None,
        },
        {
            "id": 1629645,
            "name": "RJ Barrett",
            "team": "TOR",
            "position": "SF",
            "points": 21.8,
            "rebounds": 6.4,
            "assists": 3.8,
            "steals": 0.9,
            "blocks": 0.4,
            "turnovers": 2.2,
            "image_url": None,
        },
        {
            "id": 1628778,
            "name": "Mikal Bridges",
            "team": "NYK",
            "position": "SF",
            "points": 19.6,
            "rebounds": 4.5,
            "assists": 3.7,
            "steals": 1.7,
            "blocks": 0.5,
            "turnovers": 1.8,
            "image_url": None,
        },
        # Power Forwards
        {
            "id": 1626169,
            "name": "Pascal Siakam",
            "team": "IND",
            "position": "PF",
            "points": 21.3,
            "rebounds": 7.8,
            "assists": 3.7,
            "steals": 1.0,
            "blocks": 0.6,
            "turnovers": 2.4,
            "image_url": None,
        },
        {
            "id": 1628960,
            "name": "Bam Adebayo",
            "team": "MIA",
            "position": "PF",
            "points": 19.3,
            "rebounds": 10.4,
            "assists": 3.5,
            "steals": 1.2,
            "blocks": 0.8,
            "turnovers": 2.5,
            "image_url": None,
        },
        {
            "id": 203076,
            "name": "Anthony Davis",
            "team": "LAL",
            "position": "PF",
            "points": 24.7,
            "rebounds": 12.6,
            "assists": 3.5,
            "steals": 1.1,
            "blocks": 2.3,
            "turnovers": 2.4,
            "image_url": None,
        },
        {
            "id": 1628400,
            "name": "Lauri Markkanen",
            "team": "UTA",
            "position": "PF",
            "points": 23.2,
            "rebounds": 8.2,
            "assists": 1.9,
            "steals": 0.8,
            "blocks": 0.7,
            "turnovers": 1.7,
            "image_url": None,
        },
        {
            "id": 1629649,
            "name": "Scottie Barnes",
            "team": "TOR",
            "position": "PF",
            "points": 19.9,
            "rebounds": 8.2,
            "assists": 6.1,
            "steals": 1.3,
            "blocks": 0.8,
            "turnovers": 2.9,
            "image_url": None,
        },
        {
            "id": 1630530,
            "name": "Evan Mobley",
            "team": "CLE",
            "position": "PF",
            "points": 18.0,
            "rebounds": 9.4,
            "assists": 2.9,
            "steals": 1.2,
            "blocks": 1.7,
            "turnovers": 1.6,
            "image_url": None,
        },
        # Centers
        {
            "id": 203999,
            "name": "Nikola Jokic",
            "team": "DEN",
            "position": "C",
            "points": 26.4,
            "rebounds": 12.4,
            "assists": 9.0,
            "steals": 1.4,
            "blocks": 0.9,
            "turnovers": 3.0,
            "image_url": None,
        },
        {
            "id": 1641705,
            "name": "Victor Wembanyama",
            "team": "SAS",
            "position": "C",
            "points": 25.0,
            "rebounds": 11.5,
            "assists": 3.1,
            "steals": 1.0,
            "blocks": 3.1,
            "turnovers": 2.4,
            "image_url": None,
        },
        {
            "id": 203954,
            "name": "Joel Embiid",
            "team": "PHI",
            "position": "C",
            "points": 34.7,
            "rebounds": 11.0,
            "assists": 5.6,
            "steals": 1.2,
            "blocks": 1.7,
            "turnovers": 3.6,
            "image_url": None,
        },
        {
            "id": 1188555,
            "name": "Karl-Anthony Towns",
            "team": "NYK",
            "position": "C",
            "points": 21.8,
            "rebounds": 8.3,
            "assists": 3.0,
            "steals": 0.8,
            "blocks": 0.6,
            "turnovers": 2.7,
            "image_url": None,
        },
        {
            "id": 203497,
            "name": "Rudy Gobert",
            "team": "MIN",
            "position": "C",
            "points": 14.0,
            "rebounds": 12.9,
            "assists": 1.3,
            "steals": 0.8,
            "blocks": 2.1,
            "turnovers": 1.7,
            "image_url": None,
        },
        {
            "id": 1628463,
            "name": "Jaren Jackson Jr.",
            "team": "MEM",
            "position": "C",
            "points": 22.2,
            "rebounds": 6.2,
            "assists": 2.3,
            "steals": 0.9,
            "blocks": 3.0,
            "turnovers": 2.1,
            "image_url": None,
        },
        {
            "id": 201572,
            "name": "Brook Lopez",
            "team": "MIL",
            "position": "C",
            "points": 14.8,
            "rebounds": 5.4,
            "assists": 1.7,
            "steals": 0.7,
            "blocks": 2.8,
            "turnovers": 1.2,
            "image_url": None,
        },
        {
            "id": 1627734,
            "name": "Domantas Sabonis",
            "team": "SAC",
            "position": "C",
            "points": 19.9,
            "rebounds": 13.6,
            "assists": 8.0,
            "steals": 1.1,
            "blocks": 0.5,
            "turnovers": 3.1,
            "image_url": None,
        },
        # ── 擴充球員池（2025-26 賽季） ──────────────────────────────
        # Point Guards
        {
            "id": 1630169,
            "name": "Tyrese Haliburton",
            "team": "IND",
            "position": "PG",
            "points": 22.7,
            "rebounds": 3.9,
            "assists": 10.9,
            "steals": 1.5,
            "blocks": 0.4,
            "turnovers": 2.7,
            "image_url": None,
        },
        {
            "id": 1628973,
            "name": "Jalen Brunson",
            "team": "NYK",
            "position": "PG",
            "points": 28.7,
            "rebounds": 3.6,
            "assists": 6.7,
            "steals": 0.9,
            "blocks": 0.2,
            "turnovers": 2.8,
            "image_url": None,
        },
        {
            "id": 1628368,
            "name": "De'Aaron Fox",
            "team": "SAC",
            "position": "PG",
            "points": 25.2,
            "rebounds": 4.4,
            "assists": 6.3,
            "steals": 1.5,
            "blocks": 0.3,
            "turnovers": 2.9,
            "image_url": None,
        },
        # Shooting Guards
        {
            "id": 1629639,
            "name": "Tyler Herro",
            "team": "MIA",
            "position": "SG",
            "points": 24.5,
            "rebounds": 5.3,
            "assists": 5.1,
            "steals": 0.9,
            "blocks": 0.2,
            "turnovers": 2.8,
            "image_url": None,
        },
        {
            "id": 203078,
            "name": "Bradley Beal",
            "team": "PHX",
            "position": "SG",
            "points": 18.0,
            "rebounds": 4.0,
            "assists": 5.0,
            "steals": 0.8,
            "blocks": 0.3,
            "turnovers": 2.4,
            "image_url": None,
        },
        {
            "id": 1631114,
            "name": "Jalen Williams",
            "team": "OKC",
            "position": "SG",
            "points": 24.3,
            "rebounds": 4.5,
            "assists": 5.9,
            "steals": 1.3,
            "blocks": 0.6,
            "turnovers": 2.5,
            "image_url": None,
        },
        {
            "id": 1630524,
            "name": "Devin Vassell",
            "team": "SAS",
            "position": "SG",
            "points": 19.5,
            "rebounds": 3.5,
            "assists": 3.8,
            "steals": 1.2,
            "blocks": 0.4,
            "turnovers": 1.8,
            "image_url": None,
        },
        # Small Forwards
        {
            "id": 1628384,
            "name": "OG Anunoby",
            "team": "NYK",
            "position": "SF",
            "points": 14.7,
            "rebounds": 4.8,
            "assists": 1.7,
            "steals": 1.5,
            "blocks": 0.7,
            "turnovers": 1.3,
            "image_url": None,
        },
        {
            "id": 203952,
            "name": "Andrew Wiggins",
            "team": "GSW",
            "position": "SF",
            "points": 20.0,
            "rebounds": 5.1,
            "assists": 2.5,
            "steals": 1.2,
            "blocks": 0.8,
            "turnovers": 1.8,
            "image_url": None,
        },
        {
            "id": 203114,
            "name": "Khris Middleton",
            "team": "MIL",
            "position": "SF",
            "points": 15.1,
            "rebounds": 5.3,
            "assists": 4.6,
            "steals": 1.0,
            "blocks": 0.3,
            "turnovers": 2.0,
            "image_url": None,
        },
        # Power Forwards
        {
            "id": 203944,
            "name": "Julius Randle",
            "team": "NYK",
            "position": "PF",
            "points": 24.0,
            "rebounds": 9.9,
            "assists": 5.0,
            "steals": 1.0,
            "blocks": 0.3,
            "turnovers": 3.5,
            "image_url": None,
        },
        {
            "id": 204001,
            "name": "Kristaps Porzingis",
            "team": "BOS",
            "position": "PF",
            "points": 20.1,
            "rebounds": 7.2,
            "assists": 1.5,
            "steals": 0.6,
            "blocks": 1.9,
            "turnovers": 1.5,
            "image_url": None,
        },
        {
            "id": 202331,
            "name": "Paul George",
            "team": "PHI",
            "position": "PF",
            "points": 22.6,
            "rebounds": 5.2,
            "assists": 3.5,
            "steals": 1.5,
            "blocks": 0.4,
            "turnovers": 2.1,
            "image_url": None,
        },
        # Centers
        {
            "id": 1641706,
            "name": "Chet Holmgren",
            "team": "OKC",
            "position": "C",
            "points": 18.0,
            "rebounds": 7.0,
            "assists": 1.5,
            "steals": 0.5,
            "blocks": 2.8,
            "turnovers": 1.5,
            "image_url": None,
        },
        {
            "id": 1631168,
            "name": "Alperen Sengun",
            "team": "HOU",
            "position": "C",
            "points": 21.1,
            "rebounds": 9.3,
            "assists": 5.6,
            "steals": 0.8,
            "blocks": 0.7,
            "turnovers": 3.0,
            "image_url": None,
        },
        {
            "id": 1626167,
            "name": "Myles Turner",
            "team": "IND",
            "position": "C",
            "points": 13.8,
            "rebounds": 6.4,
            "assists": 1.0,
            "steals": 0.8,
            "blocks": 2.5,
            "turnovers": 1.3,
            "image_url": None,
        },
    ]


def get_seed_player_stats(player_id: int) -> list[dict[str, Any]]:
    player = next((item for item in get_seed_players() if int(item["id"]) == player_id), None)
    team = str(player["team"]) if player else "N/A"
    stats_by_player = {
        201939: [24.3, 25.5, 29.4, 26.4],
        2544: [30.3, 28.9, 25.7, 25.7],
        203999: [27.1, 24.5, 26.4, 26.4],
        1629029: [28.4, 32.4, 33.9, 33.9],
        203507: [29.9, 31.1, 30.4, 30.4],
        201142: [29.9, 29.1, 27.1, 27.1],
        1628983: [24.5, 31.4, 30.1, 30.1],
        1641705: [0.0, 21.4, 24.3, 25.0],
        1628369: [26.9, 30.1, 26.9, 26.9],
        1630162: [21.3, 24.6, 25.9, 25.9],
        1629627: [27.0, 26.0, 22.9, 22.9],
    }
    points = stats_by_player.get(player_id, [20.0, 22.0, 24.0, 23.0])
    seasons = ["2021-22", "2022-23", "2023-24", "2024-25"]
    return [
        {
            "season": season,
            "team": team,
            "games": 72 + index,
            "points": point,
            "rebounds": round(6.0 + index, 1),
            "assists": round(5.0 + index * 0.5, 1),
            "steals": round(1.0 + index * 0.1, 1),
            "blocks": round(0.5 + index * 0.1, 1),
            "turnovers": round(2.0 + index * 0.2, 1),
        }
        for index, (season, point) in enumerate(zip(seasons, points, strict=True))
    ]


def get_seed_polls() -> list[dict[str, Any]]:
    return [
        {
            "title": "2026 NBA Finals 冠軍預測",
            "category": "champion",
            "options": ["Oklahoma City Thunder", "New York Knicks", "Cleveland Cavaliers"],
        },
        {
            "title": "2026 Finals MVP 預測",
            "category": "finals",
            "options": [
                "Shai Gilgeous-Alexander",
                "Jalen Williams",
                "Chet Holmgren",
                "Jalen Brunson",
                "Karl-Anthony Towns",
                "Mikal Bridges",
                "Donovan Mitchell",
                "Evan Mobley",
            ],
        },
        {
            "title": "2025-26 球季 MVP 你的選擇",
            "category": "mvp",
            "options": ["Shai Gilgeous-Alexander", "Nikola Jokic", "Giannis Antetokounmpo", "Luka Doncic"],
        },
    ]


def get_seed_matchups() -> list[dict[str, Any]]:
    return [
        {
            "id": "old-vs-new",
            "title": "Spurs Inspired Young Core vs NBA Superstars",
            "team_a_name": "Spurs Inspired Young Core",
            "team_b_name": "NBA Superstars",
            "team_a_players": [
                "Victor Wembanyama",
                "Anthony Edwards",
                "Shai Gilgeous-Alexander",
                "Jayson Tatum",
                "Zion Williamson",
            ],
            "team_b_players": [
                "Stephen Curry",
                "LeBron James",
                "Kevin Durant",
                "Nikola Jokic",
                "Giannis Antetokounmpo",
            ],
        },
        {
            "id": "next-gen-vs-legends",
            "title": "Next Gen Superstars vs Proven Champions",
            "team_a_name": "Next Gen",
            "team_b_name": "Proven Champions",
            "team_a_players": [
                "Victor Wembanyama",
                "Anthony Edwards",
                "Shai Gilgeous-Alexander",
                "Paolo Banchero",
                "Evan Mobley",
            ],
            "team_b_players": [
                "Stephen Curry",
                "LeBron James",
                "Kevin Durant",
                "Nikola Jokic",
                "Giannis Antetokounmpo",
            ],
        },
        {
            "id": "east-vs-west",
            "title": "Eastern All-Stars vs Western All-Stars",
            "team_a_name": "Eastern All-Stars",
            "team_b_name": "Western All-Stars",
            "team_a_players": [
                "Jayson Tatum",
                "Donovan Mitchell",
                "Giannis Antetokounmpo",
                "Karl-Anthony Towns",
                "Evan Mobley",
            ],
            "team_b_players": [
                "Shai Gilgeous-Alexander",
                "Luka Doncic",
                "Anthony Davis",
                "Nikola Jokic",
                "Victor Wembanyama",
            ],
        },
    ]


def get_seed_officials(game_id: str) -> list[dict[str, Any]]:
    _data: dict[str, list[dict[str, Any]]] = {
        "seed-001": [
            {"name": "Scott Foster", "jersey_num": "30"},
            {"name": "Kane Fitzgerald", "jersey_num": "10"},
            {"name": "Phenizee Ransom", "jersey_num": "71"},
        ],
        "seed-002": [
            {"name": "Tony Brothers", "jersey_num": "25"},
            {"name": "Ed Malloy", "jersey_num": "13"},
            {"name": "John Goble", "jersey_num": "77"},
        ],
        "recent-001": [
            {"name": "Scott Foster", "jersey_num": "30"},
            {"name": "Marc Davis", "jersey_num": "8"},
            {"name": "Rodney Mott", "jersey_num": "71"},
        ],
        "recent-002": [
            {"name": "Jason Phillips", "jersey_num": "12"},
            {"name": "James Capers", "jersey_num": "19"},
            {"name": "Suyash Mehta", "jersey_num": "65"},
        ],
        "recent-003": [
            {"name": "Tony Brothers", "jersey_num": "25"},
            {"name": "Sean Wright", "jersey_num": "42"},
            {"name": "CJ Washington", "jersey_num": "61"},
        ],
    }
    return _data.get(game_id, [])
